name: "Deploy Stack: PLZ-Connectivity"

on:
    workflow_dispatch:
        inputs:
            action:
                description: "Action: Plan, Apply, Destroy"
                required: true
                default: plan
                type: choice
                options:
                    - plan
                    - apply
                    - destroy
    pull_request:
        paths:
            - ".github/workflows/stack_plz_connectivity.yml"
            - "variables/plz-connectivity.tfvars"
            - "deployments/plz-connectivity/**"
        branches:
            - main

permissions:
    id-token: write
    contents: read

jobs:
    # PLAN ------------------------------------------------------- #
    plan:
        uses: ./.github/workflows/terraform-plan.yml
        with:
            # Inputs passed to template job.
            stack_name: plz-connectivity
            working_directory: ./deployments/plz-connectivity
            run_mode: ${{ inputs.action }}
        secrets:
            # Secrets must be declared separately from inputs and passed explicitly.
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            VPN_LOCAL_PSK: ${{ secrets.VPN_LOCAL_PSK }}

    # APPLY / DESTROY -------------------------------------------- #
    apply:
        needs: plan # REQUIRES the plan job to succeed before running.
        if:
            github.event.inputs.action == 'apply' || github.event.inputs.action ==
            'destroy'
        uses: ./.github/workflows/terraform-apply.yml
        with:
            # Inputs passed to template job.
            stack_name: plz-connectivity
            working_directory: ./deployments/plz-connectivity
            run_mode: ${{ inputs.action }}
        secrets:
            # Secrets must be declared separately from inputs and passed explicitly.
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
